<?php

declare(strict_types=1);
/**
 * Testing Str
 * 
 * @see 
 * 
 * @author Sven Schrodt<sven@schrodt.nrw>
 * @link https://github.com/SchrodtSven/BuzzCode
 * @package BuzzCode
 * @version 0.1
 * @since 2023-04-26
 */

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\DataProvider;
use SchrodtSven\BuzzCode\Type\Str;

class StrTest extends TestCase
{
    #[DataProvider('caseProvider')]
    public function testCases(string $lc, string $uc, string $lcf, string $ucf): void
    {
        $str = new Str($lc);
        $this->assertSame($str->up(false)->raw(), $uc);
        $this->assertSame($str->ucf(false)->raw(), $ucf);
        $this->assertSame($str->lcf(false)->raw(), $lcf);
    }


    public static function caseProvider(): array
    {
        return [
            ["bazola", "BAZOLA", "bazola", "Bazola"],
            ["placeholder ", "PLACEHOLDER ", "placeholder ", "Placeholder "],
            ["preferred metasyntactic variables include blurgle", "PREFERRED METASYNTACTIC VARIABLES INCLUDE BLURGLE", "preferred metasyntactic variables include blurgle", "Preferred metasyntactic variables include blurgle"],
            ["eek", "EEK", "eek", "Eek"],
            ["ook", "OOK", "ook", "Ook"],
            ["frodo", "FRODO", "frodo", "Frodo"],
            ["and bilbo; wibble", "AND BILBO; WIBBLE", "and bilbo; wibble", "And bilbo; wibble"],
            ["wobble", "WOBBLE", "wobble", "Wobble"],
            ["and in emergencies wubble; flob", "AND IN EMERGENCIES WUBBLE; FLOB", "and in emergencies wubble; flob", "And in emergencies wubble; flob"],
            ["ztesch", "ZTESCH", "ztesch", "Ztesch"],
            ["blarg", "BLARG", "blarg", "Blarg"],
            ["flarp", "FLARP", "flarp", "Flarp"],
            ["gosmacs", "GOSMACS", "gosmacs", "Gosmacs"],
            ["foo", "FOO", "foo", "Foo"],
            ["bar", "BAR", "bar", "Bar"],
            ["baz", "BAZ", "baz", "Baz"],
            ["bongo", "BONGO", "bongo", "Bongo"],
            ["bar", "BAR", "bar", "Bar"],
            ["baz", "BAZ", "baz", "Baz"],
            ["quux", "QUUX", "quux", "Quux"],
            ["quuux", "QUUUX", "quuux", "Quuux"],
            ["quuuux", "QUUUUX", "quuuux", "Quuuux"],
            ["foo", "FOO", "foo", "Foo"],
            ["bar", "BAR", "bar", "Bar"],
            ["bletch", "BLETCH", "bletch", "Bletch"],
            ["foo", "FOO", "foo", "Foo"],
            ["bar", "BAR", "bar", "Bar"],
            ["fum", "FUM", "fum", "Fum"],
            ["foo", "FOO", "foo", "Foo"],
            ["bar", "BAR", "bar", "Bar"],
            ["thud", "THUD", "thud", "Thud"],
            ["grunt", "GRUNT", "grunt", "Grunt"],
            ["foo", "FOO", "foo", "Foo"],
            ["bar", "BAR", "bar", "Bar"],
            ["zot", "ZOT", "zot", "Zot"],
            ["fred", "FRED", "fred", "Fred"],
            ["jim", "JIM", "jim", "Jim"],
            ["sheila", "SHEILA", "sheila", "Sheila"],
            ["barney", "BARNEY", "barney", "Barney"],
            ["oogle", "OOGLE", "oogle", "Oogle"],
            ["foogle", "FOOGLE", "foogle", "Foogle"],
            ["boogle", "BOOGLE", "boogle", "Boogle"],
            ["zork", "ZORK", "zork", "Zork"],
            ["gork", "GORK", "gork", "Gork"],
            ["bork", "BORK", "bork", "Bork"],
            ["pippo", "PIPPO", "pippo", "Pippo"],
            ["pluto", "PLUTO", "pluto", "Pluto"],
            ["paperino", "PAPERINO", "paperino", "Paperino"],
            ["pippo ", "PIPPO ", "pippo ", "Pippo "],
            ["peepo", "PEEPO", "peepo", "Peepo"],
            ["paperino ", "PAPERINO ", "paperino ", "Paperino "],
            ["papereeno", "PAPEREENO", "papereeno", "Papereeno"],
            ["goofy", "GOOFY", "goofy", "Goofy"],
            ["shme", "SHME", "shme", "Shme"],
            ["berkeley", "BERKELEY", "berkeley", "Berkeley"],
            ["geoWorks", "GEOWORKS", "geoWorks", "GeoWorks"],
            ["ingres", "INGRES", "ingres", "Ingres"],
            ["shme", "SHME", "shme", "Shme"],
            ["snork", "SNORK", "snork", "Snork"],
            ["spam", "SPAM", "spam", "Spam"],
            ["eggs", "EGGS", "eggs", "Eggs"],
            ["toto", "TOTO", "toto", "Toto"],
            ["titi", "TITI", "titi", "Titi"],
            ["tata", "TATA", "tata", "Tata"],
            ["tutu", "TUTU", "tutu", "Tutu"],
            ["zxc", "ZXC", "zxc", "Zxc"],
            ["spqr", "SPQR", "spqr", "Spqr"],
            ["wombat", "WOMBAT", "wombat", "Wombat"],
            ["end names", "END NAMES", "end names", "End names"],
            ["fill wordz", "FILL WORDZ", "fill wordz", "Fill wordz"],
            ["metasyntactix", "METASYNTACTIX", "metasyntactix", "Metasyntactix"],
            ["abstract", "ABSTRACT", "abstract", "Abstract"],
            ["acme", "ACME", "acme", "Acme"],
            ["alice", "ALICE", "alice", "Alice"],
            ["bar", "BAR", "bar", "Bar"],
            ["base", "BASE", "base", "Base"],
            ["baz", "BAZ", "baz", "Baz"],
            ["bean", "BEAN", "bean", "Bean"],
            ["bob", "BOB", "bob", "Bob"],
            ["claude", "CLAUDE", "claude", "Claude"],
            ["container", "CONTAINER", "container", "Container"],
            ["dependency", "DEPENDENCY", "dependency", "Dependency"],
            ["doe", "DOE", "doe", "Doe"],
            ["factory", "FACTORY", "factory", "Factory"],
            ["fnord", "FNORD", "fnord", "Fnord"],
            ["foo", "FOO", "foo", "Foo"],
            ["gadget", "GADGET", "gadget", "Gadget"],
            ["how ", "HOW ", "how ", "How "],
            ["interface", "INTERFACE", "interface", "Interface"],
            ["jackdaws ", "JACKDAWS ", "jackdaws ", "Jackdaws "],
            ["john ", "JOHN ", "john ", "John "],
            ["kroog", "KROOG", "kroog", "Kroog"],
            ["leet", "LEET", "leet", "Leet"],
            ["lorem ", "LOREM ", "lorem ", "Lorem "],
            ["nonce ", "NONCE ", "nonce ", "Nonce "],
            ["noob", "NOOB", "noob", "Noob"],
            ["pack ", "PACK ", "pack ", "Pack "],
            ["pear", "PEAR", "pear", "Pear"],
            ["pearl", "PEARL", "pearl", "Pearl"],
            ["banana", "BANANA", "banana", "Banana"],
            ["tom", "TOM", "tom", "Tom"],
            ["dick", "DICK", "dick", "Dick"],
            ["harry", "HARRY", "harry", "Harry"],
            ["wombat", "WOMBAT", "wombat", "Wombat"],
            ["frog", "FROG", "frog", "Frog"],
            ["fish", "FISH", "fish", "Fish"],
            ["womble and so on and on (see foo", "WOMBLE AND SO ON AND ON (SEE FOO", "womble and so on and on (see foo", "Womble and so on and on (see foo"],
            ["provider", "PROVIDER", "provider", "Provider"],
            ["proxy", "PROXY", "proxy", "Proxy"],
            ["quick ", "QUICK ", "quick ", "Quick "],
            ["raboof", "RABOOF", "raboof", "Raboof"],
            ["singleton", "SINGLETON", "singleton", "Singleton"],
            ["smurf", "SMURF", "smurf", "Smurf"],
            ["sphinx ", "SPHINX ", "sphinx ", "Sphinx "],
            ["supplier", "SUPPLIER", "supplier", "Supplier"],
            ["the ", "THE ", "the ", "The "],
            ["trait", "TRAIT", "trait", "Trait"],
            ["waltz ", "WALTZ ", "waltz ", "Waltz "],
            ["widget", "WIDGET", "widget", "Widget"],
            ["zapalice", "ZAPALICE", "zapalice", "Zapalice"],
            ["zonk", "ZONK", "zonk", "Zonk"],
            ["bad ", "BAD ", "bad ", "Bad "],
            ["big ", "BIG ", "big ", "Big "],
            ["black ", "BLACK ", "black ", "Black "],
            ["box ", "BOX ", "box ", "Box "],
            ["boxing ", "BOXING ", "boxing ", "Boxing "],
            ["bugs ", "BUGS ", "bugs ", "Bugs "],
            ["daft ", "DAFT ", "daft ", "Daft "],
            ["dozen ", "DOZEN ", "dozen ", "Dozen "],
            ["dwarf ", "DWARF ", "dwarf ", "Dwarf "],
            ["five ", "FIVE ", "five ", "Five "],
            ["fjord ", "FJORD ", "fjord ", "Fjord "],
            ["for ", "FOR ", "for ", "For "],
            ["fubar", "FUBAR", "fubar", "Fubar"],
            ["jargon", "JARGON", "jargon", "Jargon"],
            ["html", "HTML", "html", "Html"],
            ["m", "M", "m", "M"],
            ["metasyntactic-variable.html", "METASYNTACTIC-VARIABLE.HTML", "metasyntactic-variable.html", "Metasyntactic-variable.html"],
            ["i", "I", "i", "I"],
            ["ipsum", "IPSUM", "ipsum", "Ipsum"],
            ["j", "J", "j", "J"],
            ["jigs ", "JIGS ", "jigs ", "Jigs "],
            ["jocks ", "JOCKS ", "jocks ", "Jocks "],
            ["judge ", "JUDGE ", "judge ", "Judge "],
            ["jugs ", "JUGS ", "jugs ", "Jugs "],
            ["jump ", "JUMP ", "jump ", "Jump "],
            ["jumping ", "JUMPING ", "jumping ", "Jumping "],
            ["liquor ", "LIQUOR ", "liquor ", "Liquor "],
            ["love ", "LOVE ", "love ", "Love "],
            ["metasyntactic variable", "METASYNTACTIC VARIABLE", "metasyntactic variable", "Metasyntactic variable"],
            ["my ", "MY ", "my ", "My "],
            ["naming", "NAMING", "naming", "Naming"],
            ["nymph ", "NYMPH ", "nymph ", "Nymph "],
            ["of ", "OF ", "of ", "Of "],
            ["quartz ", "QUARTZ ", "quartz ", "Quartz "],
            ["quick ", "QUICK ", "quick ", "Quick "],
            ["quickly ", "QUICKLY ", "quickly ", "Quickly "],
            ["quiz ", "QUIZ ", "quiz ", "Quiz "],
            ["sphinx ", "SPHINX ", "sphinx ", "Sphinx "],
            ["to ", "TO ", "to ", "To "],
            ["vex ", "VEX ", "vex ", "Vex "],
            ["vex! ", "VEX! ", "vex! ", "Vex! "],
            ["vow ", "VOW ", "vow ", "Vow "],
            ["waltz ", "WALTZ ", "waltz ", "Waltz "],
            ["with ", "WITH ", "with ", "With "],
            ["wizards ", "WIZARDS ", "wizards ", "Wizards "],
            ["word", "WORD", "word", "Word"],
            ["yzzy", "YZZY", "yzzy", "Yzzy"],
            ["zebras ", "ZEBRAS ", "zebras ", "Zebras "]
        ];
    }
}
